### ISSUE TITLE
SCAM SCAM SCAM SCAM SCAM

### ISSUE THREAD

**Issue by Elinore88** [mevbotsethandbsc/mev-bot#1]
SCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAMSCAM SCAM SCAM SCAM SCAM

**Comment by mevbotsethandbsc** [comment]
Hi Eleinore, can you please describe to me why you think its a scam? Did you launch the contract?
